### PR TITLE
docs: Add examples for awscc_lightsail_*

### PR DESCRIPTION
**Pull request by acwwat**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

### CODE REVIEW

**Comment by quixoticmonk** [comment]
Reviewing this . Thank you for the contribution @acwwat . Please split these PRs by the resources in future.

**Comment by acwwat** [comment]
@quixoticmonk Thanks and understood. It would also be great if the guidance on one PR per resource/data source can be included in the contributor guide (if I didn't miss it).

**Comment by quixoticmonk** [comment]
Thank you for bringing that up. It is not a strict requirement for contributing to have the examples to be split by PRs, but it does help us to review these across the deployment lifecycles and to map any issues tied to a resource like in the case of lightsail_instance with https://github.com/hashicorp/terraform-provider-awscc/issues/1819 or the lightsail_database one listed at https://github.com/hashicorp/terraform-provider-awscc/issues/1818.

**Comment by quixoticmonk** [comment]
- awscc_lightsail_bucket : `security.tf` example leads to recreation of instance due to #1819 
- awscc_lightsail_container: No issues noted
- awscc_lightsail_disk: Might one of the idempotency issues on subsequent applies.
- awscc_lightsail_static_ip: No issues found on resource, instance issue comes up here with the example.
- awscc_lightsail_certificate : No issues noted
- awscc_lightsail_database : #1818

### Pending review:
- awscc_lightsail_distribution
- awscc_lightsail_alarm
- awscc_lightsail_load_balancer
- awscc_lightsail_load_balancer_tls_certificate

**Comment by quixoticmonk** [comment]
@acwwat Could you add tags to the applicable resources ? maybe in one of the resources when there are multiple examples.

You could use the below example ( some may have keys with patterns)
```
  tags = [{
    key   = "Modified By"
    value = "AWSCC"
  }]
```

**Review by quixoticmonk — APPROVED** [review]

**Comment by acwwat** [comment]
@quixoticmonk I've added the `tags` argument to the first (or only) example for supported resources. Please re-review, thanks.

**Review by quixoticmonk — APPROVED** [review]
LGTM

**Comment by justinretzolk** [comment]
Thank you for the contribution @acwwat 🎉

**Pull request merged**
