### PR TITLE
Feat: Unsuppress controltower landing zone

### LINKED ISSUE #1519: Resource Suppression: `aws_controltower_landing_zone`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

This resource has a empty property declaration for: `manifest` which is causing generation to fail.

### Affected Resource(s)

- aws_controltower_landing_zone (manifest)

### Schema Definition

https://github.com/hashicorp/terraform-provider-awscc/blob/ee1f5a1a210c875d1459d09803391c3e4f4bdb34/internal/service/cloudformation/schemas/AWS_ControlTower_LandingZone.json#L59

### References

- #156

### PR DESCRIPTION
**Pull request by wellsiau-aws**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Root level attribute with type undefined is now treated as JSON string as per this [commit](https://github.com/hashicorp/terraform-provider-awscc/commit/d500806c4fa8b7581b744abfd2f1ffe6a013fed4). This will also allow us to unsuppress this resource.

Relates OR Closes #1519

### CODE REVIEW

**Comment by wellsiau-aws** [comment]
pending test

**Comment by wellsiau-aws** [comment]
Test results
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # awscc_controltower_landing_zone.test will be created
  + resource "awscc_controltower_landing_zone" "test" {
      + arn                      = (known after apply)
      + drift_status             = (known after apply)
      + id                       = (known after apply)
      + landing_zone_identifier  = (known after apply)
      + latest_available_version = (known after apply)
      + manifest                 = jsonencode(
            {
              + accessManagement      = {
                  + enabled = true
                }
              + centralizedLogging    = {
                  + accountId      = "582159568573"
                  + configurations = {
                      + accessLoggingBucket = {
                          + retentionDays = 60
                        }
                      + loggingBucket       = {
                          + retentionDays = 60
                        }
                    }
                  + enabled        = true
                }
              + governedRegions       = [
                  + "us-west-2",
                  + "us-east-1",
                ]
              + organizationStructure = {
                  + sandbox  = {
                      + name = "Sandbox"
                    }
                  + security = {
                      + name = "Core"
                    }
                }
              + securityRoles         = {
                  + accountId = "674305394241"
                }
            }
        )
      + status                   = (known after apply)
      + tags                     = (known after apply)
      + version                  = "3.3"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

awscc_controltower_landing_zone.test: Creating...
awscc_controltower_landing_zone.test: Still creating... [10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [1m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [1m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [1m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [1m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [1m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [1m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [2m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [2m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [2m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [2m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [2m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [2m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [3m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [3m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [3m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [3m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [3m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [3m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [4m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [4m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [4m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [4m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [4m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [4m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [5m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [5m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [5m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [5m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [5m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [5m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [6m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [6m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [6m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [6m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [6m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [6m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [7m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [7m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [7m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [7m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [7m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [7m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [8m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [8m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [8m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [8m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [8m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [8m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [9m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [9m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [9m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [9m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [9m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [9m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [10m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [10m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [10m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [10m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [10m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [10m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [11m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [11m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [11m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [11m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [11m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [11m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [12m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [12m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [12m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [12m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [12m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [12m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [13m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [13m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [13m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [13m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [13m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [13m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [14m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [14m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [14m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [14m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [14m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [14m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [15m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [15m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [15m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [15m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [15m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [15m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [16m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [16m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [16m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [16m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [16m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [16m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [17m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [17m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [17m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [17m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [17m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [17m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [18m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [18m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [18m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [18m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [18m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [18m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [19m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [19m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [19m20s elapsed]
awscc_controltower_landing_zone.test: Still creating... [19m30s elapsed]
awscc_controltower_landing_zone.test: Still creating... [19m40s elapsed]
awscc_controltower_landing_zone.test: Still creating... [19m50s elapsed]
awscc_controltower_landing_zone.test: Still creating... [20m0s elapsed]
awscc_controltower_landing_zone.test: Still creating... [20m10s elapsed]
awscc_controltower_landing_zone.test: Still creating... [20m20s elapsed]
awscc_controltower_landing_zone.test: Creation complete after 20m25s [id=arn:aws:controltower:us-east-1:473390604243:landingzone/M221H03ROHRYLORP]
```

**Review by quixoticmonk — APPROVED** [review]

**Review by BondAnthony — APPROVED** [review]
Nice!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@wellsiau-aws Thanks for the contribution :tada: :clap:.

**Pull request merged**
