### PR TITLE
docs: awscc_rds_db_instance

### LINKED ISSUE #935: Update documentation to add/include Sample Example Usage for awscc_rds_db_instance
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### New or Affected Resource(s)

* awscc_rds_db_instance

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #Link https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/rds_db_instance#nestedatt--master_user_secret

### PR DESCRIPTION
**Pull request by ishwar-amzn**
Tested and added sample usage example for awscc_rds_db_instance.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #935

### CODE REVIEW

**Comment by ishwar-amzn** [comment]
Added and tested sample code successfully.

```
Terraform will perform the following actions:

  # aws_kms_key.example will be created
  + resource "aws_kms_key" "example" {
      + arn                                = (known after apply)
      + bypass_policy_lockout_safety_check = false
      + customer_master_key_spec           = "SYMMETRIC_DEFAULT"
      + description                        = "Example KMS Key"
      + enable_key_rotation                = false
      + id                                 = (known after apply)
      + is_enabled                         = true
      + key_id                             = (known after apply)
      + key_usage                          = "ENCRYPT_DECRYPT"
      + multi_region                       = (known after apply)
      + policy                             = (known after apply)
      + tags_all                           = (known after apply)
    }

  # awscc_rds_db_instance.default will be created
  + resource "awscc_rds_db_instance" "default" {
      + allocated_storage                        = "10"
      + allow_major_version_upgrade              = (known after apply)
      + associated_roles                         = (known after apply)
      + auto_minor_version_upgrade               = (known after apply)
      + availability_zone                        = (known after apply)
      + backup_retention_period                  = (known after apply)
      + ca_certificate_identifier                = (known after apply)
      + certificate_details                      = (known after apply)
      + certificate_rotation_restart             = (known after apply)
      + character_set_name                       = (known after apply)
      + copy_tags_to_snapshot                    = (known after apply)
      + custom_iam_instance_profile              = (known after apply)
      + db_cluster_identifier                    = (known after apply)
      + db_cluster_snapshot_identifier           = (known after apply)
      + db_instance_arn                          = (known after apply)
      + db_instance_class                        = "db.t3.micro"
      + db_instance_identifier                   = (known after apply)
      + db_name                                  = "mydb"
      + db_parameter_group_name                  = "default.mysql5.7"
      + db_security_groups                       = (known after apply)
      + db_snapshot_identifier                   = (known after apply)
      + db_subnet_group_name                     = (known after apply)
      + db_system_id                             = (known after apply)
      + dbi_resource_id                          = (known after apply)
      + delete_automated_backups                 = (known after apply)
      + deletion_protection                      = (known after apply)
      + domain                                   = (known after apply)
      + domain_iam_role_name                     = (known after apply)
      + enable_cloudwatch_logs_exports           = (known after apply)
      + enable_iam_database_authentication       = (known after apply)
      + enable_performance_insights              = (known after apply)
      + endpoint                                 = (known after apply)
      + engine                                   = "mysql"
      + engine_version                           = "5.7"
      + id                                       = (known after apply)
      + iops                                     = (known after apply)
      + kms_key_id                               = (known after apply)
      + license_model                            = (known after apply)
      + manage_master_user_password              = (known after apply)
      + master_user_password                     = "foobarbaz"
      + master_user_secret                       = (known after apply)
      + master_username                          = "foo"
      + max_allocated_storage                    = (known after apply)
      + monitoring_interval                      = (known after apply)
      + monitoring_role_arn                      = (known after apply)
      + multi_az                                 = (known after apply)
      + nchar_character_set_name                 = (known after apply)
      + network_type                             = (known after apply)
      + option_group_name                        = (known after apply)
      + performance_insights_kms_key_id          = (known after apply)
      + performance_insights_retention_period    = (known after apply)
      + port                                     = (known after apply)
      + preferred_backup_window                  = (known after apply)
      + preferred_maintenance_window             = (known after apply)
      + processor_features                       = (known after apply)
      + promotion_tier                           = (known after apply)
      + publicly_accessible                      = (known after apply)
      + replica_mode                             = (known after apply)
      + restore_time                             = (known after apply)
      + source_db_cluster_identifier             = (known after apply)
      + source_db_instance_automated_backups_arn = (known after apply)
      + source_db_instance_identifier            = (known after apply)
      + source_dbi_resource_id                   = (known after apply)
      + source_region                            = (known after apply)
      + storage_encrypted                        = (known after apply)
      + storage_throughput                       = (known after apply)
      + storage_type                             = (known after apply)
      + tags                                     = (known after apply)
      + tde_credential_arn                       = (known after apply)
      + tde_credential_password                  = (known after apply)
      + timezone                                 = (known after apply)
      + use_default_processor_features           = (known after apply)
      + use_latest_restorable_time               = (known after apply)
      + vpc_security_groups                      = (known after apply)
    }

  # awscc_rds_db_instance.default_one will be created
  + resource "awscc_rds_db_instance" "default_one" {
      + allocated_storage                        = "10"
      + allow_major_version_upgrade              = (known after apply)
      + associated_roles                         = (known after apply)
      + auto_minor_version_upgrade               = (known after apply)
      + availability_zone                        = (known after apply)
      + backup_retention_period                  = (known after apply)
      + ca_certificate_identifier                = (known after apply)
      + certificate_details                      = (known after apply)
      + certificate_rotation_restart             = (known after apply)
      + character_set_name                       = (known after apply)
      + copy_tags_to_snapshot                    = (known after apply)
      + custom_iam_instance_profile              = (known after apply)
      + db_cluster_identifier                    = (known after apply)
      + db_cluster_snapshot_identifier           = (known after apply)
      + db_instance_arn                          = (known after apply)
      + db_instance_class                        = "db.t3.micro"
      + db_instance_identifier                   = (known after apply)
      + db_name                                  = "mydb"
      + db_parameter_group_name                  = "default.mysql5.7"
      + db_security_groups                       = (known after apply)
      + db_snapshot_identifier                   = (known after apply)
      + db_subnet_group_name                     = (known after apply)
      + db_system_id                             = (known after apply)
      + dbi_resource_id                          = (known after apply)
      + delete_automated_backups                 = (known after apply)
      + deletion_protection                      = (known after apply)
      + domain                                   = (known after apply)
      + domain_iam_role_name                     = (known after apply)
      + enable_cloudwatch_logs_exports           = (known after apply)
      + enable_iam_database_authentication       = (known after apply)
      + enable_performance_insights              = (known after apply)
      + endpoint                                 = (known after apply)
      + engine                                   = "mysql"
      + engine_version                           = "5.7"
      + id                                       = (known after apply)
      + iops                                     = (known after apply)
      + kms_key_id                               = (known after apply)
      + license_model                            = (known after apply)
      + manage_master_user_password              = true
      + master_user_password                     = (known after apply)
      + master_user_secret                       = (known after apply)
      + master_username                          = "foo"
      + max_allocated_storage                    = (known after apply)
      + monitoring_interval                      = (known after apply)
      + monitoring_role_arn                      = (known after apply)
      + multi_az                                 = (known after apply)
      + nchar_character_set_name                 = (known after apply)
      + network_type                             = (known after apply)
      + option_group_name                        = (known after apply)
      + performance_insights_kms_key_id          = (known after apply)
      + performance_insights_retention_period    = (known after apply)
      + port                                     = (known after apply)
      + preferred_backup_window                  = (known after apply)
      + preferred_maintenance_window             = (known after apply)
      + processor_features                       = (known after apply)
      + promotion_tier                           = (known after apply)
      + publicly_accessible                      = (known after apply)
      + replica_mode                             = (known after apply)
      + restore_time                             = (known after apply)
      + source_db_cluster_identifier             = (known after apply)
      + source_db_instance_automated_backups_arn = (known after apply)
      + source_db_instance_identifier            = (known after apply)
      + source_dbi_resource_id                   = (known after apply)
      + source_region                            = (known after apply)
      + storage_encrypted                        = (known after apply)
      + storage_throughput                       = (known after apply)
      + storage_type                             = (known after apply)
      + tags                                     = (known after apply)
      + tde_credential_arn                       = (known after apply)
      + tde_credential_password                  = (known after apply)
      + timezone                                 = (known after apply)
      + use_default_processor_features           = (known after apply)
      + use_latest_restorable_time               = (known after apply)
      + vpc_security_groups                      = (known after apply)
    }

  # awscc_rds_db_instance.default_two will be created
  + resource "awscc_rds_db_instance" "default_two" {
      + allocated_storage                        = "10"
      + allow_major_version_upgrade              = (known after apply)
      + associated_roles                         = (known after apply)
      + auto_minor_version_upgrade               = (known after apply)
      + availability_zone                        = (known after apply)
      + backup_retention_period                  = (known after apply)
      + ca_certificate_identifier                = (known after apply)
      + certificate_details                      = (known after apply)
      + certificate_rotation_restart             = (known after apply)
      + character_set_name                       = (known after apply)
      + copy_tags_to_snapshot                    = (known after apply)
      + custom_iam_instance_profile              = (known after apply)
      + db_cluster_identifier                    = (known after apply)
      + db_cluster_snapshot_identifier           = (known after apply)
      + db_instance_arn                          = (known after apply)
      + db_instance_class                        = "db.t3.micro"
      + db_instance_identifier                   = (known after apply)
      + db_name                                  = "mydb"
      + db_parameter_group_name                  = "default.mysql5.7"
      + db_security_groups                       = (known after apply)
      + db_snapshot_identifier                   = (known after apply)
      + db_subnet_group_name                     = (known after apply)
      + db_system_id                             = (known after apply)
      + dbi_resource_id                          = (known after apply)
      + delete_automated_backups                 = (known after apply)
      + deletion_protection                      = (known after apply)
      + domain                                   = (known after apply)
      + domain_iam_role_name                     = (known after apply)
      + enable_cloudwatch_logs_exports           = (known after apply)
      + enable_iam_database_authentication       = (known after apply)
      + enable_performance_insights              = (known after apply)
      + endpoint                                 = (known after apply)
      + engine                                   = "mysql"
      + engine_version                           = "5.7"
      + id                                       = (known after apply)
      + iops                                     = (known after apply)
      + kms_key_id                               = (known after apply)
      + license_model                            = (known after apply)
      + manage_master_user_password              = true
      + master_user_password                     = (known after apply)
      + master_user_secret                       = {
          + kms_key_id = (known after apply)
          + secret_arn = (known after apply)
        }
      + master_username                          = "foo"
      + max_allocated_storage                    = (known after apply)
      + monitoring_interval                      = (known after apply)
      + monitoring_role_arn                      = (known after apply)
      + multi_az                                 = (known after apply)
      + nchar_character_set_name                 = (known after apply)
      + network_type                             = (known after apply)
      + option_group_name                        = (known after apply)
      + performance_insights_kms_key_id          = (known after apply)
      + performance_insights_retention_period    = (known after apply)
      + port                                     = (known after apply)
      + preferred_backup_window                  = (known after apply)
      + preferred_maintenance_window             = (known after apply)
      + processor_features                       = (known after apply)
      + promotion_tier                           = (known after apply)
      + publicly_accessible                      = (known after apply)
      + replica_mode                             = (known after apply)
      + restore_time                             = (known after apply)
      + source_db_cluster_identifier             = (known after apply)
      + source_db_instance_automated_backups_arn = (known after apply)
      + source_db_instance_identifier            = (known after apply)
      + source_dbi_resource_id                   = (known after apply)
      + source_region                            = (known after apply)
      + storage_encrypted                        = (known after apply)
      + storage_throughput                       = (known after apply)
      + storage_type                             = (known after apply)
      + tags                                     = (known after apply)
      + tde_credential_arn                       = (known after apply)
      + tde_credential_password                  = (known after apply)
      + timezone                                 = (known after apply)
      + use_default_processor_features           = (known after apply)
      + use_latest_restorable_time               = (known after apply)
      + vpc_security_groups                      = (known after apply)
    }

  # awscc_rds_db_instance.example will be created
  + resource "awscc_rds_db_instance" "example" {
      + allocated_storage                        = "50"
      + allow_major_version_upgrade              = (known after apply)
      + associated_roles                         = (known after apply)
      + auto_minor_version_upgrade               = (known after apply)
      + availability_zone                        = (known after apply)
      + backup_retention_period                  = (known after apply)
      + ca_certificate_identifier                = (known after apply)
      + certificate_details                      = (known after apply)
      + certificate_rotation_restart             = (known after apply)
      + character_set_name                       = (known after apply)
      + copy_tags_to_snapshot                    = (known after apply)
      + custom_iam_instance_profile              = (known after apply)
      + db_cluster_identifier                    = (known after apply)
      + db_cluster_snapshot_identifier           = (known after apply)
      + db_instance_arn                          = (known after apply)
      + db_instance_class                        = (known after apply)
      + db_instance_identifier                   = (known after apply)
      + db_name                                  = (known after apply)
      + db_parameter_group_name                  = (known after apply)
      + db_security_groups                       = (known after apply)
      + db_snapshot_identifier                   = (known after apply)
      + db_subnet_group_name                     = (known after apply)
      + db_system_id                             = (known after apply)
      + dbi_resource_id                          = (known after apply)
      + delete_automated_backups                 = (known after apply)
      + deletion_protection                      = (known after apply)
      + domain                                   = (known after apply)
      + domain_iam_role_name                     = (known after apply)
      + enable_cloudwatch_logs_exports           = (known after apply)
      + enable_iam_database_authentication       = (known after apply)
      + enable_performance_insights              = (known after apply)
      + endpoint                                 = (known after apply)
      + engine                                   = (known after apply)
      + engine_version                           = (known after apply)
      + id                                       = (known after apply)
      + iops                                     = (known after apply)
      + kms_key_id                               = (known after apply)
      + license_model                            = (known after apply)
      + manage_master_user_password              = (known after apply)
      + master_user_password                     = (known after apply)
      + master_user_secret                       = (known after apply)
      + master_username                          = (known after apply)
      + max_allocated_storage                    = 100
      + monitoring_interval                      = (known after apply)
      + monitoring_role_arn                      = (known after apply)
      + multi_az                                 = (known after apply)
```

**Comment by rahul-amzn** [comment]
Please add *.tf and *.md.tmpl files.

**Review by wellsiau-aws — CHANGES_REQUESTED** [review]
thanks for the contribution! can you please include the remaining files such as the `.tf` and the `tmpl` files. See example [here](https://github.com/hashicorp/terraform-provider-awscc/pull/934/files)

**Comment by ishwar-amzn** [comment]
Included the remaining files such as the .tf and the tmpl files.

**Comment by rahul-amzn** [comment]
> Included the remaining files such as the .tf and the tmpl files.

@ishwar-amzn please re-run `terraform fmt`

**Comment by ishwar-amzn** [comment]
Thank you @rahul-amzn for quick review and suggestions. I have formatted code with terraform fmt.

**Review by wellsiau-aws — APPROVED** [review]
LGTM

**Comment by breathingdust** [comment]
Hi @ishwar-amzn! It [looks](https://github.com/hashicorp/terraform-provider-awscc/actions/runs/5010931037/jobs/9219314207?pr=936) like the generated output does not match what has been committed. Can you rerun `make docs` and commit any resulting changed files if they look correct?

**Comment by ewbankkit** [comment]
@ishwar-amzn Thanks for the contribution :tada: :clap:.

**Pull request merged**
