### PR TITLE
2024-12-05 Schema Updates

### PR DESCRIPTION
**Pull request by jar-b**
### Description

CloudFormation schema updates as of 2024-12-05.

```console
% TF_LOG=ERROR make testacc PKG_NAME=internal/aws/logs TESTARGS='-run=TestAccAWSLogsLogGroup_\|TestAccAWSLogsLogGroupDataSource_'
TF_ACC=1 go test ./internal/aws/logs -v -count 1 -parallel 20 -run=TestAccAWSLogsLogGroup_\|TestAccAWSLogsLogGroupDataSource_ -timeout 180m

2024-12-05T14:07:26.089-0500 [ERROR] sdk.proto: Response contains error diagnostic: tf_req_id=30516e2e-9b1d-06b5-0b71-937abd4bb649 tf_rpc=ReadDataSource tf_data_source_type=awscc_logs_log_group tf_provider_addr=registry.terraform.io/hashicorp/awscc diagnostic_summary="AWS Data Source Not Found" diagnostic_detail="After attempting to read the data source, the API returned a resource not found error for the id provided. Original Error: couldn't find resource" diagnostic_severity=ERROR tf_proto_version=6.7
--- PASS: TestAccAWSLogsLogGroupDataSource_NonExistent (1.01s)
--- PASS: TestAccAWSLogsLogGroup_basic (23.68s)
--- PASS: TestAccAWSLogsLogGroupDataSource_basic (23.83s)
--- PASS: TestAccAWSLogsLogGroup_disappears (29.10s)
--- PASS: TestAccAWSLogsLogGroup_update (31.02s)
PASS
ok      github.com/hashicorp/terraform-provider-awscc/internal/aws/logs 31.837s
```

### CODE REVIEW

**Comment by quixoticmonk** [comment]
Are the `AWS::SageMaker::Cluster` schema still excluded from the schema refresh ? The `CustomMetadata` issue which was present on the last schema was removed by the service team.

**Comment by jar-b** [comment]
I'll take a look and see if we can re-generate without issue now.

**Comment by jar-b** [comment]
Smoke tests still passing after removing suppression for AWS SageMaker cluster schema changes.

```console
% TF_LOG=ERROR make testacc PKG_NAME=internal/aws/logs TESTARGS='-run=TestAccAWSLogsLogGroup_\|TestAccAWSLogsLogGroupDataSource_'
TF_ACC=1 go test ./internal/aws/logs -v -count 1 -parallel 20 -run=TestAccAWSLogsLogGroup_\|TestAccAWSLogsLogGroupDataSource_ -timeout 180m

2024-12-05T15:11:30.924-0500 [ERROR] sdk.proto: Response contains error diagnostic: diagnostic_severity=ERROR tf_data_source_type=awscc_logs_log_group tf_req_id=46c1ae9b-0cb8-6a11-dd1d-9767c79eabb3 tf_provider_addr=registry.terraform.io/hashicorp/awscc tf_proto_version=6.7 tf_rpc=ReadDataSource diagnostic_summary="AWS Data Source Not Found" diagnostic_detail="After attempting to read the data source, the API returned a resource not found error for the id provided. Original Error: couldn't find resource"
--- PASS: TestAccAWSLogsLogGroupDataSource_NonExistent (0.98s)
--- PASS: TestAccAWSLogsLogGroupDataSource_basic (21.14s)
--- PASS: TestAccAWSLogsLogGroup_basic (26.20s)
--- PASS: TestAccAWSLogsLogGroup_disappears (26.67s)
--- PASS: TestAccAWSLogsLogGroup_update (34.23s)
PASS
ok      github.com/hashicorp/terraform-provider-awscc/internal/aws/logs 35.243
```

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀

**Pull request merged**
