### PR TITLE
Added an exception to otherwise optional argument to the docs

### PR DESCRIPTION
**Pull request by henryk-rychlik**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Relates OR Closes #0000

### CODE REVIEW

**Comment by quixoticmonk** [comment]
Thank you for the contribution @henryk-rychlik. The documentation is auto-generated based on the Cloudformation schema for the resource and would be overridden in the next build. Let me followup with the team to see if we can add details on the `resource_properties` to clarify the priority requirement. Would you be able to open an issue on this that I can track against ?

@wellsiau-aws FYI

**Comment by henryk-rychlik** [comment]
Understood. Whatever it is generated from, seems to be wrong then. Not specifying the priority for a DNS resource results in an error message. This is reflected in CF docs, but not mentioned on the provider side:
> ResourceProperties
    If the DNS resource is a DNS Firewall rule group, this indicates the priority.
    Required: No

Source:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53profiles-profileresourceassociation.html

I think you mean this one:
>     "ResourceProperties" : {
      "description" : "A JSON-formatted string with key-value pairs specifying the properties of the associated resource.",
      "type" : "string"
    },
    
Source:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html

The two don't match. Who is responsible for this? I would assume AWS?

**Comment by quixoticmonk** [comment]
The description does come from the schema that is produced that you have linked. The description of fields in the schema published is different and I have opened an internal ticket to bring them to sync with the service team. Thank you for raising this.

**Comment by henryk-rychlik** [comment]
Awesome, I will go ahead and close the PR as it was just a stub either way.

**Pull request closed without merging**
